# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - structure_controller
    - needle_controller

  structure_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_zx
      - joint_xy
  needle_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_needle
      - link_2_aux_joint
      - link_2_joint
      - link_3_aux_joint
      - link_3_joint
      - link_4_aux_joint
      - link_4_joint
      - link_5_aux_joint
      - link_5_joint